apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: http-port
    protocol: TCP
    port: 9000
    targetPort: 80
